inherit_from: .rubocop_todo.yml
AllCops:
  Exclude:
    - 'bin/localhost'
Metrics/LineLength:
  Max: 240
Metrics/BlockLength:
  Max: 240
Style/SymbolArray:
  EnforcedStyle: brackets
Naming/RescuedExceptionsVariableName:
  PreferredName: error
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
